pushd tree-sitter & git pull origin master & popd
pushd tree-sitter-agda & git pull origin master & popd
pushd tree-sitter-bash & git pull origin master & popd
pushd tree-sitter-c & git pull origin master & popd
pushd tree-sitter-c-sharp & git pull origin master & popd
pushd tree-sitter-cpp & git pull origin master & popd
pushd tree-sitter-css & git pull origin master & popd
pushd tree-sitter-embedded-template & git pull origin master & popd
pushd tree-sitter-go & git pull origin master & popd
pushd tree-sitter-haskell & git pull origin master & popd
pushd tree-sitter-html & git pull origin master & popd
pushd tree-sitter-java & git pull origin master & popd
pushd tree-sitter-javascript & git pull origin master & popd
pushd tree-sitter-jsdoc & git pull origin master & popd
pushd tree-sitter-json & git pull origin master & popd
pushd tree-sitter-julia & git pull origin master & popd
pushd tree-sitter-ocaml & git pull origin master & popd
pushd tree-sitter-php & git pull origin master & popd
pushd tree-sitter-python & git pull origin master & popd
pushd tree-sitter-ql & git pull origin master & popd
pushd tree-sitter-razor & git pull origin master & popd
pushd tree-sitter-ruby & git pull origin master & popd
pushd tree-sitter-rust & git pull origin master & popd
pushd tree-sitter-scala & git pull origin master & popd
pushd tree-sitter-swift & git pull origin master & popd
pushd tree-sitter-toml & git pull origin master & popd
pushd tree-sitter-tsq & git pull origin master & popd
pushd tree-sitter-typescript & git pull origin master & popd
pushd tree-sitter-verilog & git pull origin master & popd
